# Name of your workflow (shows up in the "Actions" tab in GitHub)
name: Build and Push Docker Image to Docker Hub

# When this workflow should run
on:
  # Run it manually from the Actions tab
  workflow_dispatch:
  # Run it automatically whenever you push changes to the 'main' branch
  push:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build_and_push:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    # Define the steps within the job
    steps:
      # Step 1: Check out your repository code
      - name: Check out code
        uses: actions/checkout@v4 # Uses a pre-built action

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use secrets (explained below)
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Use secrets (explained below)

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the current directory (where the Dockerfile is)
          file: ./Dockerfile # Specify the Dockerfile name
          push: true # Actually push the image to Docker Hub
          tags: dgolum11/runpod-video-processor:latest # Your image name and tag